---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: ubuntu:latest
  commands:
  - sleep 20
  - echo "THIS WORKS"

- name: greeting
  image: ubuntu:latest
  commands:
  - sleep 20
  - echo "2nd run"
