---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: ubuntu:latest
  commands:
  - echo "THIS WORKS"
  depends_on: ["clone"]
  
- name: greeting2
  image: ubuntu:latest
  commands:
  - echo "2nd run"
  depends_on: ["clone"]
  
- name: discord
  image: appleboy/drone-discord
  settings:
    webhook_id: 622638418673008676
    webhook_token: Zdh_UDxxBCF5RnTF1lSvmkiEZQNLgfaHYMrcElmLW52FBekY6rDmdl7sw3WRAn9IQWZT
    message: "THIS IS A TEST MESSAGE"
  depends_on: 
    - greeting
    - greeting2
